// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ODYhgRy_Y65bPMVHw5KY8syDk2-ZBcg',
    appId: '1:253520933683:web:067885c30dc681b9cbc446',
    messagingSenderId: '253520933683',
    projectId: 'roguestore-5b345',
    authDomain: 'roguestore-5b345.firebaseapp.com',
    storageBucket: 'roguestore-5b345.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzw9UkgehghYLqPUfOlvnI96JMSt0ClHE',
    appId: '1:253520933683:android:09a6c193e8e64eb6cbc446',
    messagingSenderId: '253520933683',
    projectId: 'roguestore-5b345',
    storageBucket: 'roguestore-5b345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNLHEqbAC3-Uy_ADIQBckal11WiWKoHI',
    appId: '1:253520933683:ios:d5a16bbb9d08a61ecbc446',
    messagingSenderId: '253520933683',
    projectId: 'roguestore-5b345',
    storageBucket: 'roguestore-5b345.appspot.com',
    androidClientId: '253520933683-jcp5pqavvdkte8hi9pvb11do2iem2nja.apps.googleusercontent.com',
    iosClientId: '253520933683-i3dpi91fut5kfkv7gg9l8aogmj6fc5lu.apps.googleusercontent.com',
    iosBundleId: 'com.roguestore.roguestoreAdminPanel',
  );

}